x16_1_1_first_need   
x16_1_1_first_need_other                                                                            
x16_1_2_second_need                                                                                   
x16_1_2_second_need_other                                                                            
x16_1_3_third_need                                                                                   
x16_1_3_third_need_other                                                                              
x16_2_at_present_how_would_you_rate_your_h_hs_ability_to_meet_the_basic_needs_basic_needs_are_things_like_shelter_food_medicine_of_all_members           
x16_3_1_first_reason          
x16_3_1_first_reason_other     
x16_3_2_second_reason         
x16_3_2_second_reason_other   
x16_3_3_third_reason         
x16_3_3_third_reason_other   
x16_4_would_you_accept_to_be_asked_about_your_household_income_in_the_last_month 
if_yes_do_you_earn_your_income_in_syp_or_try 
rent                                   
shelter_maintenance    
food                  
electricity        
other_fuel_incl_firewood_gas_for_cooking_h            
education_services_incl_fees_uniforms_books          
health_care_including_visit_to_health_facility_medical_procedure_medicines 
disability_related_costs_not_included_in_the_health_care_costs 
clothing                                                           
water                                                              
hygiene_items                                                      
non_food_items_household_cooking_pot_lamp_blankets 
transportation_incl_fuel                                                                               
phone_data_communication                                                                               
debt_payment 